### PR TITLE
Fix thread safety issue in directory creation

### PR DESCRIPTION
**Pull request by bhansaliraunak**
https://github.com/IBM/terratorch/issues/17

### CODE REVIEW

**Comment by bhansaliraunak** [comment]
@CarlosGomes98, could you please review this pull request? Your feedback would be greatly appreciated.

**Review by Joao-L-S-Almeida — APPROVED** [review]

**Comment by bhansaliraunak** [comment]
@Joao-L-S-Almeida It seems I don't have a write access to do merge pull requests. 
Can you either provide a one or please do the merge PR?

**Comment by romeokienzler** [comment]
thanks a lot @bhansaliraunak for your contribution - we'll review/merge in our next community call this week

**Review by romeokienzler — COMMENTED** [review]
lgtm!

**Pull request merged**
