### PR TITLE
Trying to test for 3.12 (update packages if necessary)

### PR DESCRIPTION
**Pull request by Joao-L-S-Almeida**

### CODE REVIEW

**Comment by Joao-L-S-Almeida** [comment]
Seemingly the toolkit is working for python 3.10, 3.11 and 3.12 using torch == 2.3.*, considering the flexible versions defined on `requirements/required.txt`, however, perhaps we could condisider to use a discontinuous definition like   `torch<=2.1, >=2.3` if we observe some incompatibility.

**Comment by CarlosGomes98** [comment]
these requirements files should now really only be updated through accepting PRs from dependabot, and they should always have exactly pinned versions. For requirements like `torch >= 2.1.` we should add this instead in the pyproject.toml

**Comment by Joao-L-S-Almeida** [comment]
Maybe we could create a kind of conditional for the requirements when switching between versions.

**Comment by Joao-L-S-Almeida** [comment]
I defined new fixed versions for the packages in `requirements/required.txt` based in the choices made automatically by Actions . It seems that is working for all the tests and python versions.

**Comment by romeokienzler** [comment]
lgtm - fix conflicts..then merge

**Comment by romeokienzler** [comment]
thanks @Joao-L-S-Almeida 
- [x] merged

**Pull request merged**
