### PR TITLE
Allows passing metadata from datasets to models

### PR DESCRIPTION
**Pull request by PedroConrado**
This PR might look large, but the changes are generally straightforward and do not substantially alter the behavior of the datasets and models. The main changes are:

- Addition of **kwargs handling in Models (PixelWiseModel and ScalarOutputModel)
- Addition of **kwargs handling in Tasks
- Modified ViT to handle metadata
- Addition of ViT 600
- Standardization of datasets for Geobench, Sen1Floods11, Fire Scars, and MultitemporalCrop
- Tests for all modified datasets

### CODE REVIEW

**Comment by Joao-L-S-Almeida** [comment]
It seem the tests are breaking because of an outdatted  `fiona` version. Maybe you could try to update `geopandas` : https://geopandas.org/en/stable/docs/changelog.html#version-0-14-4-april-26-2024

**Comment by PedroConrado** [comment]
Thanks @Joao-L-S-Almeida, fixed it.

**Comment by PedroConrado** [comment]
I think now its happening the issue reported in #221

**Comment by Joao-L-S-Almeida** [comment]
Exaclty.

**Pull request merged**
