### PR TITLE
[WIP] Adds new datasets

### PR DESCRIPTION
**Pull request by PedroConrado**
This PR adds ForestNet, LandSlide4Sense, Burn_Intensity, CarbonFlux and BioMassters datasets.

From #237 it uses mainly:

- terratorch/datamodules/generic_multimodal_data_module.py: wrap_in_compose_is_list and MultimodalNormalize functions
- terratorch/datasets/generic_multimodal_dataset.py: MultimodalToTensor
- terratorch/models/pixel_wise_model.py changes
- terratorch/tasks/regression_tasks.py changes
- terratorch/tasks/segmentation_tasks.py

### CODE REVIEW

**Comment by romeokienzler** [comment]
depends on #237

**Comment by romeokienzler** [comment]
@PedroConrado 

I think there are some merge conflicts which are not resolved

Ideally you run:
> pytest tests/
on your branch

```
    from terratorch.datamodules.generic_multimodal_data_module import GenericMultiModalDataModule
E     File "/dccstor/wfm/users/rkie/gitco/tmp/terratorch/terratorch/datamodules/generic_multimodal_data_module.py", line 1
E       <<<<<<< HEAD
E       ^^
E   SyntaxError: invalid syntax

```

**Comment by PedroConrado** [comment]
> @PedroConrado
> 
> I think there are some merge conflicts which are not resolved
> 
> Ideally you run:
> 
> > pytest tests/
> > on your branch
> 
> ```
>     from terratorch.datamodules.generic_multimodal_data_module import GenericMultiModalDataModule
> E     File "/dccstor/wfm/users/rkie/gitco/tmp/terratorch/terratorch/datamodules/generic_multimodal_data_module.py", line 1
> E       <<<<<<< HEAD
> E       ^^
> E   SyntaxError: invalid syntax
> ```

This issure has been fixed

**Review by romeokienzler — APPROVED** [review]

**Comment by romeokienzler** [comment]
thanks @PedroConrado 

- [x] merged

**Pull request merged**
